import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeHighlight from 'rehype-highlight';
import type { Components } from 'react-markdown';

const components: Components = {
  // Render video tags from raw HTML in markdown
  p({ children, ...props }) {
    // Check if the only child is an img — if so, don't wrap in <p>
    const childArray = Array.isArray(children) ? children : [children];
    if (childArray.length === 1 && typeof childArray[0] === 'object' && childArray[0] !== null && 'type' in childArray[0] && childArray[0].type === 'img') {
      return <>{children}</>;
    }
    return <p {...props}>{children}</p>;
  },
  img({ src, alt, ...props }) {
    // Check if it's actually a video URL
    if (src && /\.(mp4|webm|mov)(\?|$)/i.test(src)) {
      return <video src={src} controls className="markdown-video" />;
    }
    return <img src={src} alt={alt || ''} className="markdown-image" loading="lazy" {...props} />;
  },
};

interface MarkdownContentProps {
  content: string;
  className?: string;
}

function normalizeMarkdownContent(content: string) {
  // Support legacy inline video HTML generated by older editor versions.
  return content.replace(
    /<video[^>]*src=["']([^"']+)["'][^>]*>\s*<\/video>/gi,
    (_match, src: string) => `![video](${src})`
  );
}

export default function MarkdownContent({ content, className }: MarkdownContentProps) {
  if (looksLikeHtml(content)) {
    return (
      <div
        className={`markdown-body ${className || ''}`}
        dangerouslySetInnerHTML={{ __html: sanitizeHtml(content) }}
      />
    );
  }

  return (
    <div className={`markdown-body ${className || ''}`}>
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        rehypePlugins={[rehypeHighlight]}
        components={components}
      >
        {normalizeMarkdownContent(content)}
      </ReactMarkdown>
    </div>
  );
}

function looksLikeHtml(content: string) {
  return /<\/?[a-z][\s\S]*>/i.test(content);
}

function sanitizeHtml(html: string) {
  if (typeof window === 'undefined') {
    return html;
  }

  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const allowedTags = new Set(['A', 'B', 'BLOCKQUOTE', 'BR', 'CODE', 'EM', 'I', 'IMG', 'LI', 'OL', 'P', 'PRE', 'STRONG', 'UL', 'VIDEO']);

  const walk = (node: Node) => {
    if (node.nodeType === Node.ELEMENT_NODE) {
      const element = node as HTMLElement;
      if (!allowedTags.has(element.tagName)) {
        const fragment = document.createDocumentFragment();
        while (element.firstChild) {
          fragment.appendChild(element.firstChild);
        }
        element.replaceWith(fragment);
        return;
      }

      const attrs = [...element.attributes];
      for (const attr of attrs) {
        const name = attr.name.toLowerCase();
        const value = attr.value.trim();
        const allowedAttr = isAllowedAttribute(element.tagName, name);
        const safeUrl = name === 'href' || name === 'src' ? isSafeUrl(value) : true;
        if (!allowedAttr || !safeUrl) {
          element.removeAttribute(attr.name);
        }
      }

      if (element.tagName === 'A') {
        element.setAttribute('target', '_blank');
        element.setAttribute('rel', 'noopener noreferrer nofollow');
      }
      if (element.tagName === 'VIDEO') {
        element.setAttribute('controls', '');
        element.classList.add('markdown-video');
      }
      if (element.tagName === 'IMG') {
        element.classList.add('markdown-image');
        element.setAttribute('loading', 'lazy');
      }
    }

    const children = [...node.childNodes];
    for (const child of children) {
      walk(child);
    }
  };

  walk(doc.body);
  return doc.body.innerHTML;
}

function isAllowedAttribute(tagName: string, attrName: string) {
  if (tagName === 'A') {
    return ['href', 'target', 'rel'].includes(attrName);
  }
  if (tagName === 'IMG') {
    return ['src', 'alt', 'class', 'loading'].includes(attrName);
  }
  if (tagName === 'VIDEO') {
    return ['src', 'controls', 'class'].includes(attrName);
  }
  return false;
}

function isSafeUrl(value: string) {
  return /^(https?:|\/)/i.test(value);
}
